 CREATE TABLE employees (
  name varchar(255) default NULL,
  phone varchar(100) default NULL,
  email varchar(255) default NULL,
  addres varchar(255) default NULL,
  city varchar(50) default NULL,
  zip varchar(10) default NULL,
  state varchar(50) default NULL,
  country varchar(50) default NULL,
  date varchar(50) default NULL,
  custom varchar(255) default NULL,
  rname varchar(255) default NULL,
  ophone varchar(100) default NULL,
  altemail varchar(255) default NULL,
  altcity varchar(50) default NULL,
  altzip varchar(10) default NULL
);


INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Ivory I. Hawkins','(452) 561-6447','consectetuer.ipsum@Duis.org','8642 Lorem, Road','Hagerstown','U5T 6K8','Quebec','Rwanda','Jun 15, 2012','S8K 8L8','Galena','(222) 369-6075','sit.amet@felisadipiscing.org','Worland','L2E 7P4');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Iliana G. Gallagher','(816) 758-0716','lorem.eu.metus@facilisisnonbibendum.com','Ap #124-9273 Nonummy Street','Pomona','K8N 1L9','Kentucky','United States','Feb 24, 2013','B4U 1F9','Paloma','(974) 415-6855','laoreet.ipsum@Nunclaoreetlectus.com','Areceibo','45668');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Kylan Y. Mcintyre','(130) 337-1025','Vestibulum@Proin.com','P.O. Box 747, 1298 Nullam Ave','Moscow','99266','MB','New Caledonia','Dec 18, 2012','D4Y 9P0','Bree','(228) 341-0127','et@intempus.ca','Seal Beach','59970');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Candace E. Hardy','(630) 231-3606','est@adipiscinglobortisrisus.com','171-6393 Vulputate Road','Cary','46844','NU','Bulgaria','Dec 30, 2013','D3N 3S2','Giacomo','(434) 159-6916','montes.nascetur@tinciduntvehicula.ca','Kokomo','K4A 2K1');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Fay O. Mack','(882) 126-3769','sit.amet@Pellentesqueutipsum.ca','Ap #528-1396 Felis St.','Atwater','54968','Oklahoma','Ecuador','Aug 22, 2013','Z9M 5I2','Demetria','(385) 165-5810','vulputate.eu.odio@eutelluseu.org','Tonawanda','K1E 7U0');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Aladdin Y. Reed','(532) 754-5151','Vivamus.sit.amet@Inatpede.edu','P.O. Box 443, 5672 Mattis Avenue','Victoria','99677','PE','Sweden','Sep 8, 2013','Y9L 4M5','Zeph','(720) 701-6029','cursus.luctus@hendreritconsectetuer.edu','Cruz Bay','X9B 4P3');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Dustin G. Lee','(797) 394-5016','euismod@orciadipiscingnon.org','P.O. Box 922, 7310 Parturient Rd.','International Falls','Q4H 1Y5','Nova Scotia','Morocco','Jul 12, 2012','J3A 9K1','Kevyn','(682) 155-6743','vel@amet.ca','Beloit','P4W 4M2');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Alfonso R. Santos','(170) 226-9575','Mauris@ante.ca','8561 Ligula. Street','Fernley','28213','NT','Honduras','Mar 22, 2013','H1O 5V5','Baker','(501) 937-7605','dignissim.lacus@eusem.edu','Pasco','54480');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Julie H. Finley','(688) 549-0419','libero.Morbi.accumsan@euultricessit.ca','642-8748 Pede, St.','Marquette','V1S 3Z7','NB','Tunisia','Oct 9, 2012','W5W 8A9','Samson','(885) 487-4132','leo.in.lobortis@tristique.com','Hagerstown','01005');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Britanni J. Wynn','(682) 780-5758','Aliquam.ornare@metus.org','P.O. Box 706, 2044 Malesuada Road','MayagÃ¼ez','Y6D 9R6','OR','Egypt','May 3, 2013','L3I 9D8','Scarlett','(711) 576-8030','feugiat.placerat@a.org','Worland','10528');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Amelia G. Hughes','(472) 660-2817','lorem.eu@orcilacus.edu','Ap #801-3657 Lacinia. St.','Boise','12874','Prince Edward Island','Portugal','Jul 18, 2013','C7K 1A2','Elliott','(891) 453-1789','Proin@vitaesodalesat.edu','Minnetonka','S2U 6C9');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Hall S. Cox','(737) 165-9795','sem@posuere.edu','8158 Dui. Avenue','Cerritos','W8Q 6N7','Kentucky','Faroe Islands','Jun 6, 2013','C6X 6Q6','Latifah','(277) 568-9567','Integer.mollis.Integer@tellusjusto.org','Eden Prairie','L8B 4G7');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Merritt K. Frye','(690) 351-0266','pretium@tincidunt.com','6184 Ut Av.','Lynchburg','T9B 8I2','West Virginia','Mali','Nov 13, 2012','Z8B 1W2','Shad','(634) 807-8864','eu.metus@Maecenas.ca','Arlington','15785');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Ferdinand N. Golden','(236) 165-6094','lacinia@maurisut.com','P.O. Box 147, 7377 Felis Road','Birmingham','L3Q 2C1','NC','Guam','Mar 28, 2014','T5X 3N8','Stacey','(652) 690-9106','elit@rutrum.ca','Eufaula','97064');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Shellie D. Young','(485) 873-4360','pede@Maecenasornareegestas.ca','7869 Orci Rd.','Biddeford','06786','MB','Turkey','Dec 13, 2012','H9U 0H2','Halla','(936) 620-3962','ultrices.Vivamus.rhoncus@eu.com','Salem','01865');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Constance V. Lang','(238) 452-3889','at@non.org','P.O. Box 590, 6557 Enim, Av.','Milford','G6M 1G0','Prince Edward Island','Reunion','Jan 29, 2013','W6Z 2M8','Brenden','(673) 728-5442','scelerisque@tempusnon.edu','New Iberia','29613');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Naomi H. Simmons','(384) 866-4491','lorem.ut@Aeneanegetmetus.com','4976 Feugiat. St.','Rancho Palos Verdes','C6M 1G6','Yukon','El Salvador','Jun 20, 2012','F0X 8L3','Rebekah','(696) 408-3188','Quisque.nonummy.ipsum@purusactellus.org','Winooski','14661');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Timon K. Terrell','(982) 419-9163','rutrum@enimcondimentum.com','425-7055 Vel St.','Azusa','L3U 2W9','WV','Mali','Oct 20, 2012','I7N 2V1','Lev','(962) 306-4502','urna.Nullam@milacinia.edu','Rocky Mount','07447');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Abdul B. Watkins','(743) 569-5318','porta.elit@mollis.ca','P.O. Box 245, 2609 Sociis Rd.','Glendale','94738','NL','El Salvador','Jun 25, 2012','W6X 8D2','Adele','(968) 346-7989','nonummy@Proinegetodio.org','Merizo','M1U 3N8');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Joy M. Harvey','(425) 625-2077','placerat.Cras.dictum@montesnasceturridiculus.com','985-5141 Amet Av.','Steubenville','Z8G 2J1','Quebec','Cape Verde','Oct 2, 2012','T2R 0I4','Pascale','(194) 742-6721','quam.dignissim@rutrum.ca','Fredericksburg','00661');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Minerva X. Sanders','(949) 396-3901','aliquet.diam@sagittisDuisgravida.org','963-2920 Sed Av.','Frederiksted','E4H 8A4','Quebec','Dominican Republic','May 28, 2012','S2X 0G9','Casey','(638) 897-5378','ipsum.dolor@dolor.com','St. Petersburg','S4X 1U2');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Ella O. Jordan','(257) 274-5624','adipiscing.elit@mollisIntegertincidunt.org','Ap #543-3512 Sodales St.','Meadville','09406','Idaho','Poland','May 1, 2013','A7K 4G0','Malcolm','(734) 640-0575','Morbi.sit.amet@Maecenas.edu','Mechanicville','X3K 1M0');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Quyn T. Lambert','(290) 257-5930','fringilla@feliseget.ca','P.O. Box 469, 3364 Amet St.','Methuen','F8W 3H8','Idaho','Nicaragua','Jan 30, 2014','L3K 0I7','Briar','(417) 302-3066','libero.mauris@Duiselementumdui.ca','Columbia','72534');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Fuller Y. Avila','(740) 121-4386','senectus.et@vulputatemaurissagittis.org','Ap #602-6486 Bibendum St.','Norton','44998','MI','Eritrea','Apr 25, 2012','L9M 5K8','Isadora','(125) 981-6992','eros.non@Fuscedolorquam.ca','Warwick','U4I 6W3');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Teagan H. Franco','(486) 236-4862','gravida@euismod.org','944-5185 Consequat, Rd.','Indio','38296','Quebec','Tokelau','Apr 4, 2012','P4F 2X0','Whitney','(202) 407-3522','dignissim@urna.org','Lower Burrell','F2E 2A4');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Boris V. Mcdonald','(487) 488-5035','ornare.placerat.orci@sem.ca','P.O. Box 674, 3767 Phasellus Av.','Pascagoula','57188','SK','Equatorial Guinea','Jul 8, 2013','D6C 0E1','Guy','(700) 829-0017','eget.varius@semperrutrumFusce.org','Topeka','44788');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Alfonso A. Bradley','(710) 834-5444','eu.augue@Intincidunt.org','109-2147 Aliquam St.','Auburn','04383','Kansas','Micronesia','Apr 29, 2013','K4X 8Z3','Ferris','(497) 963-2872','eu@dolor.com','Mount Pleasant','68701');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Gavin P. Mccullough','(754) 787-1851','Morbi.accumsan@diamlorem.org','Ap #968-5602 Tellus Road','Seward','54434','ON','Marshall Islands','Feb 7, 2014','R1K 4I2','Willa','(578) 905-7506','risus@cursus.com','Paterson','73585');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Thane F. Grimes','(176) 496-8648','adipiscing.elit.Aliquam@rhoncusProin.edu','5263 Mauris Street','Steubenville','F7A 5G8','British Columbia','Vanuatu','Nov 22, 2012','Y5X 5K5','Zephr','(339) 850-0896','In.mi.pede@purusDuiselementum.edu','Green River','04827');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Alfreda R. Day','(612) 972-2010','Fusce.fermentum@sit.edu','649-6687 Etiam St.','Nevada City','36329','South Carolina','Gabon','Jan 18, 2013','Z8B 2B1','Hedwig','(276) 317-0317','elit@massaMaurisvestibulum.com','Basin','41859');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Mufutau Y. Terry','(591) 605-6710','aliquet.nec.imperdiet@Morbi.edu','4855 A Road','South Gate','O5V 7J4','NY','Egypt','Dec 22, 2012','U0H 3U0','Kenyon','(805) 936-7761','mauris.aliquam@DonecfringillaDonec.ca','Ketchikan','H2N 6U0');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Simone D. Mayo','(299) 347-2966','dui.semper.et@nectellus.org','257-2550 Phasellus Road','Princeton','58116','Alberta','Burundi','Oct 18, 2013','H4Q 0Q6','Maris','(329) 765-7979','dis@Suspendissesagittis.com','Pueblo','09922');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Blaine P. Goodman','(595) 262-4821','sed.consequat@convallisantelectus.org','P.O. Box 385, 4357 Nullam Ave','Kankakee','I4Z 3Q2','Vermont','Korea','Nov 2, 2013','B5S 4M9','Liberty','(964) 422-1255','magna.Duis.dignissim@estconguea.org','Charlotte Amalie','85874');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Roanna M. Chase','(489) 875-8492','felis.Nulla.tempor@nonvestibulum.org','851-8809 Pede. Ave','Shelton','76553','ME','India','Aug 18, 2013','I5F 8L6','Sloane','(730) 237-0009','Nulla.facilisis.Suspendisse@duiCumsociis.org','Joplin','X4N 5T2');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Shelly V. Boyer','(192) 780-1814','per.inceptos@velitin.edu','P.O. Box 195, 1257 Convallis Rd.','Mequon','A9U 5R0','ME','Cape Verde','Nov 10, 2013','D5F 2L3','Nerea','(162) 886-3974','Fusce.aliquet@egetmassa.ca','Yukon','X3V 7S5');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Vernon D. Skinner','(205) 576-1049','malesuada.fames.ac@molestietellusAenean.com','8067 Turpis. Rd.','Isle of Palms','83170','NB','Burundi','Nov 12, 2013','W0Q 6R7','Martha','(273) 168-3032','mi.fringilla.mi@orci.edu','Elmira','F2T 2Y1');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Guy E. Roth','(148) 700-4401','viverra@vel.org','Ap #681-5479 Non Road','Vernon','T1V 9B9','SK','Virgin Islands, U.S.','May 8, 2012','D3Z 6U9','Olga','(138) 797-1546','sociis.natoque@convalliserat.com','Greensboro','26540');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Rosalyn D. Henderson','(237) 934-0736','odio.sagittis@rhoncusProinnisl.org','P.O. Box 844, 3795 Ut Ave','International Falls','B7W 6D9','New Hampshire','Somalia','Sep 14, 2012','O3H 5A6','Donna','(770) 935-6430','dapibus.id.blandit@mattis.com','Parma','20236');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Cassandra F. Carver','(547) 500-2811','urna@sociisnatoquepenatibus.ca','987-537 Vulputate, Rd.','South Portland','71794','New Hampshire','Belarus','May 15, 2012','J1E 4I0','Kathleen','(521) 390-1351','massa.Suspendisse@cursusNuncmauris.org','Missoula','A9H 6O9');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Oleg B. Tillman','(934) 988-2911','urna@liberoDonec.org','235-5920 Ut St.','Vicksburg','P8P 3K5','UT','Zimbabwe','Sep 4, 2013','V4W 0L0','Chancellor','(547) 296-1287','sagittis@Donecegestas.org','Newcastle','25884');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Jermaine I. Spears','(973) 475-8220','ac@ut.org','3744 Aliquam Rd.','Rock Island','92851','AB','Mali','Apr 14, 2013','J7Y 1H8','Griffin','(585) 409-1060','ac.eleifend@bibendumsedest.org','Meriden','T3C 4X4');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Timon F. Erickson','(844) 670-5345','convallis@Nullafacilisis.org','541-8904 Netus Street','Tok','61501','IN','Slovenia','Jul 16, 2013','T4P 7X9','Cleo','(518) 205-1286','scelerisque@eu.ca','San Luis Obispo','08741');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Kristen X. Dickerson','(986) 978-3975','neque.Sed.eget@eudoloregestas.edu','6038 Urna Road','Duquesne','31728','NT','Ireland','May 26, 2013','H9I 0W7','Wang','(629) 891-8356','mattis.Integer.eu@ultriciesdignissim.ca','Concord','84028');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Fredericka E. Oconnor','(302) 271-7906','felis.Nulla.tempor@pellentesqueeget.org','Ap #590-5591 Donec St.','Kingston','12115','Florida','Cocos (Keeling) Islands','Feb 7, 2013','J0X 5V8','Lee','(477) 905-0205','mus.Proin.vel@mattis.ca','Laguna Beach','H5Q 5R4');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Michelle M. Beck','(653) 417-1961','sociis.natoque@Sednulla.com','Ap #185-8451 Mauris St.','Austin','D5V 6F2','UT','Belarus','Jul 23, 2013','H0V 4Z4','Mohammad','(510) 942-0938','dapibus@tempor.com','North Pole','69047');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Teagan C. Kemp','(935) 972-3933','in.hendrerit@enimcondimentum.ca','406-9109 Non, Road','Simi Valley','64978','South Carolina','Pitcairn','Sep 4, 2013','J4M 6W4','Yvette','(275) 604-9492','lacinia@ullamcorper.com','Chino Hills','18356');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Wendy B. England','(477) 316-4921','vulputate@risus.org','Ap #600-7761 Nec Ave','San Rafael','59595','Saskatchewan','Mayotte','Mar 17, 2013','A5T 7B6','Yuli','(277) 214-5990','semper.tellus.id@Aliquamadipiscinglobortis.org','Hollister','H6Y 1Z2');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Marshall V. Barber','(478) 170-8429','Lorem.ipsum.dolor@lacusvariuset.ca','Ap #771-3973 Justo. Rd.','Athens','67877','UT','Libyan Arab Jamahiriya','Jan 9, 2014','T8G 8R7','Autumn','(668) 557-0137','egestas.urna@atvelit.edu','Kokomo','85353');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Carolyn D. Barnett','(129) 790-3688','non@eleifendvitaeerat.ca','449-2073 Scelerisque Avenue','Lawndale','12358','Utah','Canada','Jul 8, 2013','V5E 8X7','Penelope','(893) 733-4278','In.mi@magnaatortor.org','Avalon','I8Z 2R7');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Hamish H. Justice','(531) 309-3466','fringilla.Donec.feugiat@Suspendisseseddolor.ca','Ap #216-2141 Felis Ave','Ponce','O5J 7E1','ND','Mongolia','Jun 27, 2012','A0N 3N2','Wynne','(339) 823-5947','eros.Proin.ultrices@Maecenas.edu','Ashland','J2Z 8W9');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Hanae B. Spears','(915) 218-4067','Aenean.euismod@loremegetmollis.ca','P.O. Box 579, 9937 Diam. Ave','DuBois','34812','NU','Gambia','Dec 31, 2013','K5L 2A5','Zelda','(792) 471-7533','ante.Nunc@Quisque.edu','Ardmore','H8Q 4R0');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Patience Q. Brady','(236) 733-6584','pede.malesuada.vel@euaccumsansed.ca','P.O. Box 476, 6441 Et, Rd.','Clarksville','X1D 4R1','Quebec','Liechtenstein','Dec 4, 2013','Z5X 6D7','Alfonso','(839) 934-5491','sem.eget@nascetur.org','Kona','S5D 6V3');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Audrey W. Sheppard','(940) 748-0473','feugiat.nec.diam@adipiscingenimmi.com','Ap #216-8236 Lobortis Street','Beaumont','O6P 2L8','DC','Saint Vincent and The Grenadines','Jun 28, 2012','W2P 9S3','Francis','(761) 616-8776','ut.pellentesque.eget@aliquet.ca','Greensburg','75257');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Zelenia P. Dyer','(385) 928-6902','neque@Maecenas.com','Ap #987-2882 Tempus Av.','Moscow','F3X 5V6','ND','Senegal','Dec 31, 2012','Q2R 2E7','Jameson','(345) 392-0623','Donec@dictummagna.org','Yigo','D4N 4D4');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Britanney S. Prince','(898) 542-9948','nec@placeratCras.ca','466-6483 At St.','Frederiksted','77318','New Brunswick','Namibia','Mar 26, 2013','M5B 6N0','Briar','(435) 983-7071','sapien.gravida@sed.ca','Hamilton','62728');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Reece H. Solomon','(499) 891-2371','Donec@euodioPhasellus.ca','1132 Erat. Av.','Dover','47265','KY','Norfolk Island','May 8, 2013','G8N 2Y7','Kylynn','(697) 789-5973','risus@ultriciesligulaNullam.org','Columbus','G7T 6A5');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Craig J. Farrell','(752) 509-3862','primis.in.faucibus@ipsum.org','Ap #845-1874 At Rd.','Reno','L4U 1L3','Prince Edward Island','Angola','Sep 22, 2013','L3Z 8E6','Austin','(983) 445-8040','mauris.Suspendisse.aliquet@cursusNunc.com','Kahului','66336');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Kiayada B. Hebert','(838) 109-9823','habitant.morbi@ac.com','5782 Mauris, St.','Fremont','A9R 7F0','Kentucky','Suriname','Feb 10, 2014','F6W 1Q7','Iliana','(902) 145-2528','natoque.penatibus.et@Crasvulputatevelit.edu','Lima','C8V 6D4');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Helen E. Green','(358) 997-0285','arcu.Vivamus.sit@sed.ca','Ap #827-4037 Velit Road','Dearborn','40601','KS','Australia','May 23, 2013','D6A 8S2','Phoebe','(308) 407-3441','orci.Ut.semper@ligulaAeneangravida.org','Oro Valley','X8U 4D4');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Jana D. Ellis','(518) 791-7747','sit.amet@tortor.ca','3840 Sed, Ave','Kearney','73357','AB','Pakistan','May 25, 2013','Y0J 8D0','Marah','(681) 401-3182','nunc.sed@mollisvitaeposuere.org','Corinth','37755');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Veronica M. Emerson','(963) 179-7510','pede.Cum.sociis@Integereu.edu','Ap #471-5598 Bibendum Street','College Park','35311','AB','Belgium','Sep 4, 2013','S1V 7V4','Susan','(902) 384-9293','Donec.feugiat.metus@necorciDonec.org','Fajardo','W2G 3N2');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Hiroko J. Dillon','(392) 681-7046','metus.Vivamus@NullaaliquetProin.org','Ap #729-2314 Donec Rd.','Valdosta','10145','Quebec','Singapore','May 3, 2013','A7Q 1L6','Lareina','(119) 956-5022','Maecenas@ligula.edu','Fulton','87665');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Mufutau O. Jenkins','(417) 872-9929','ipsum.porta@Crasdictum.edu','P.O. Box 887, 2082 Quam Av.','Leominster','A4Y 6A4','Oklahoma','Saint Lucia','Mar 1, 2013','O3A 5I2','Ignatius','(808) 415-1443','viverra.Donec.tempus@orciluctus.org','Yuma','C3S 2A3');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Stuart S. Mcclure','(910) 258-2423','Nullam@nectempusscelerisque.ca','P.O. Box 913, 7345 Lectus. St.','Burbank','V4W 9L1','Alberta','United States','Jun 18, 2013','W6V 1B0','Jescie','(142) 519-6284','imperdiet.non@lorem.ca','Chandler','A9I 9R4');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Slade D. Mann','(761) 712-1372','nisi@estcongue.ca','P.O. Box 800, 9952 Nibh St.','Dothan','A2K 9W8','NT','Cameroon','Mar 1, 2014','E2K 2Q2','Keith','(960) 250-2672','nulla.magna.malesuada@dapibus.edu','East Lansing','00305');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Jillian S. Dalton','(769) 484-3554','enim@orcilacusvestibulum.com','451-5944 Integer Rd.','Little Rock','55696','NT','Luxembourg','Jan 5, 2014','W4I 3V8','Whoopi','(385) 159-1015','magna.a.tortor@ut.com','Tyler','Y2N 8B6');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Fuller D. Wall','(739) 522-4839','tempor.arcu.Vestibulum@posuere.edu','938-9053 Vestibulum Rd.','El Segundo','W4O 7L2','North Dakota','Finland','Nov 19, 2013','F9O 6U9','Lareina','(556) 563-0020','montes@musDonecdignissim.ca','Madison','C5N 4F2');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Orlando E. Henry','(309) 355-7294','Donec.egestas@quamPellentesque.edu','4462 Sagittis. St.','Bellingham','O2A 1Q2','MO','Niger','Jul 11, 2012','M9G 9S4','Zorita','(200) 682-3018','Cras@arcuiaculis.org','Lawrenceville','87242');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Urielle U. Bryan','(837) 577-7883','ac.turpis.egestas@Donecatarcu.edu','9570 Nisi Av.','Cape Coral','40323','Nova Scotia','Belarus','Aug 20, 2013','H0Q 0W3','Tanisha','(765) 842-0918','sapien.imperdiet.ornare@dapibusligula.com','Providence','65184');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Jason T. Watson','(558) 497-1629','cursus@aliquamadipiscinglacus.org','1729 Tristique Avenue','Frederiksted','X9Y 4C8','Nunavut','Grenada','May 7, 2013','M5H 1Q8','Jemima','(590) 497-2873','Vivamus@Donec.edu','Port Huron','W6U 6H8');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Xaviera K. Ramos','(390) 245-0490','Phasellus@acurnaUt.org','2204 Eget St.','Citrus Heights','40126','BC','Taiwan, Province of China','Jul 18, 2013','D4A 5A0','Aidan','(912) 202-7046','dictum@erat.org','Half Moon Bay','28080');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Judah E. Reid','(977) 987-9901','ultrices.a.auctor@utnisia.org','679-1277 Lorem Road','Wausau','B2V 1C8','Nevada','Sierra Leone','Oct 13, 2012','O5O 5M5','Martina','(585) 569-9960','pede.Praesent.eu@In.com','Clarksburg','J7B 4I7');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Clementine F. Stokes','(736) 301-1567','magna.Praesent@augueacipsum.org','Ap #709-3170 Magna. Av.','The Dalles','66909','NB','Dominican Republic','Sep 26, 2012','O3H 6N8','Griffith','(349) 165-6423','augue.id.ante@leo.ca','Butte','U7T 6Q7');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Tanisha D. Combs','(286) 120-4200','viverra.Donec.tempus@aneque.ca','P.O. Box 710, 859 Conubia Street','Elko','W1Y 5R7','New Jersey','Malta','Jun 5, 2012','Q0O 0F5','Carson','(126) 129-3364','amet.consectetuer@sit.org','Sandy Springs','L2G 3U9');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Serena A. Horton','(452) 972-2334','tristique@nonlobortisquis.edu','165-4506 Semper Ave','Catskill','W4R 2E6','NU','Turkey','Jun 25, 2012','J8D 5G4','Adena','(617) 511-2527','massa.lobortis.ultrices@convallisdolor.com','Rolla','A8U 7E9');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Linda V. Manning','(710) 316-3915','Phasellus@semper.edu','Ap #797-4611 Sed St.','Laguna Hills','42714','MT','Burundi','Jan 31, 2013','O7H 2C2','Graiden','(637) 779-4862','enim.non@Sed.com','Whittier','76771');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Edan T. Velazquez','(129) 243-7815','at.lacus.Quisque@idmagnaet.org','Ap #500-7352 Fusce Avenue','Barrow','S8C 5Q2','SD','Algeria','Aug 28, 2013','Y2I 7D4','Delilah','(842) 404-2890','Quisque.ac.libero@nisinibhlacinia.com','Cruz Bay','S9W 7U6');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Quon X. Pitts','(140) 678-0911','amet.faucibus@diamloremauctor.com','P.O. Box 538, 1428 Adipiscing Ave','Hickory','83661','Newfoundland and Labrador','Greece','Aug 2, 2013','F0B 0B0','Clio','(246) 181-8523','lorem.sit.amet@gravida.edu','Sioux City','E2N 1I0');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Hector B. Little','(551) 572-9438','imperdiet.ornare@portaelit.org','5696 Semper Rd.','Manitowoc','77727','NB','Nauru','Apr 9, 2013','F4C 9S0','Indigo','(289) 428-0238','metus.In.lorem@neceleifend.org','Elmira','23040');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Eric G. Bennett','(712) 526-5169','accumsan.convallis@eutellusPhasellus.ca','Ap #367-154 Nunc. Rd.','Cary','74978','Hawaii','Botswana','Mar 22, 2014','M2J 1V4','Roth','(782) 740-5968','sit.amet.consectetuer@nasceturridiculus.edu','Hastings','D4O 1P3');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Charity P. Bernard','(524) 101-8392','et.rutrum@lacus.com','7539 Egestas. Av.','Ames','F2N 7F1','Oklahoma','Hong Kong','Jan 5, 2013','D9L 3T7','Dominique','(117) 211-2999','Aenean.eget.metus@non.org','Webster Groves','S1R 8T6');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Donovan N. Sykes','(722) 542-6247','Curabitur.vel@etmagnisdis.org','7208 Libero. Road','Anaconda','07866','MO','Monaco','Jan 13, 2013','S1B 2K6','Jasmine','(848) 501-1760','id.sapien@luctussitamet.com','Palo Alto','Y3L 8U2');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Idola K. Knapp','(577) 216-5016','enim@nequesed.com','P.O. Box 324, 8538 Eu Rd.','Sioux City','V2V 6X1','Northwest Territories','Fiji','Sep 18, 2012','R3X 2J0','Tamekah','(632) 570-9838','massa.lobortis.ultrices@elementumlorem.org','Elkhart','63118');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Erica O. Higgins','(638) 947-5790','nec.urna@auctorquistristique.com','P.O. Box 477, 9156 Lacinia St.','Marlborough','61082','MN','Austria','Jun 18, 2012','H7L 9H2','Victoria','(479) 402-1125','ultricies@Suspendisse.ca','Elizabeth City','21796');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Jin X. Barron','(258) 578-8472','egestas.a@auctornunc.com','P.O. Box 234, 6019 Sem Av.','Blacksburg','E4P 9I2','NM','Angola','Jan 10, 2014','D6W 0C6','Clementine','(765) 494-2168','malesuada@dignissim.org','Wisconsin Rapids','83390');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Chester D. Wilkinson','(881) 943-6180','Morbi@eget.ca','2707 Adipiscing Rd.','Anderson','29462','Kansas','Egypt','Jun 5, 2012','E9F 6G8','Quincy','(289) 521-4464','at.iaculis.quis@nunc.org','Keene','87121');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Winifred H. Kemp','(869) 256-3358','tincidunt.Donec@elit.com','8146 Convallis Rd.','Missoula','21303','Manitoba','Bulgaria','Nov 12, 2012','U3H 3A5','Moses','(642) 472-6596','sagittis@Nunc.org','New Haven','92813');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Donna D. Francis','(654) 611-2636','tempus.non@cursus.org','P.O. Box 292, 7735 Mi. St.','Oak Ridge','45027','Nova Scotia','Nepal','Apr 17, 2013','Y7U 0B4','Hyatt','(670) 966-9861','arcu.Morbi@elitCurabitursed.ca','Ada','P4S 6X8');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Cynthia Q. Sawyer','(186) 523-2328','mollis.nec.cursus@ligulaeuenim.com','P.O. Box 354, 7497 Egestas. Avenue','Cumberland','35294','MB','Central African Republic','Mar 17, 2013','I6L 6W7','Sylvester','(770) 432-6149','orci.Ut.semper@faucibusMorbi.com','Peoria','U7J 1L5');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Drake F. Rocha','(740) 537-2315','Nam.nulla@DonecfringillaDonec.ca','955-1463 Penatibus Av.','Winnemucca','Y7N 1E1','Yukon','Holy See (Vatican City State)','Oct 30, 2012','O7E 7B3','Emerald','(720) 807-6367','vulputate@sedsapienNunc.com','Racine','L1E 7C5');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Camille H. Michael','(333) 769-9779','Nulla.aliquet@turpis.edu','6449 Nullam Av.','Douglas','86604','Kansas','Uruguay','Nov 11, 2013','S2Q 4E5','Brady','(955) 485-5443','In@nequeetnunc.com','Minnetonka','82546');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Jeanette I. Hopkins','(707) 868-8131','sed.hendrerit.a@Maecenasmalesuadafringilla.com','P.O. Box 123, 3622 Aliquam Road','Moore','34889','Newfoundland and Labrador','Kyrgyzstan','Nov 24, 2013','N9D 3T2','Nora','(926) 661-7127','vulputate.risus@Loremipsum.com','Delta Junction','26064');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Austin A. Cash','(923) 750-6873','vulputate.risus@consectetuer.edu','P.O. Box 289, 8823 Fames St.','Hope','O7D 6J6','NC','Western Sahara','May 9, 2012','K3B 0F8','Irma','(765) 483-4953','Cras@elitCurabitursed.edu','Long Beach','U2W 4W6');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Hilda B. Duffy','(532) 370-9348','ultricies.adipiscing.enim@acarcuNunc.edu','P.O. Box 167, 4748 Fusce Street','Orlando','G8I 7S0','YT','Ghana','Apr 27, 2012','U0J 7K7','Leila','(163) 484-6041','ac.sem.ut@etipsum.edu','Billings','G2F 3S5');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Marcia P. Kramer','(929) 780-4142','vitae.aliquam@sempercursus.com','Ap #655-2474 Sed, Avenue','Santa Barbara','49076','NT','Korea','Feb 13, 2013','E1I 2P5','Owen','(818) 311-2199','quis.arcu@dapibusgravidaAliquam.org','St. Petersburg','34156');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Kylie U. Alvarez','(730) 488-2964','euismod@molestiedapibusligula.ca','Ap #474-7349 Quis, Av.','Corvallis','L6S 6C3','British Columbia','Croatia','Apr 22, 2012','G3A 4I7','Timon','(566) 842-6974','leo@lobortisnisinibh.org','Juneau','05914');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Honorato S. Hebert','(741) 110-5774','elit@ante.org','Ap #421-9689 Mi Street','Henderson','74376','NV','Jordan','Oct 15, 2012','S9P 7M3','Karleigh','(855) 962-4998','auctor.ullamcorper.nisl@Nuncquis.org','Agawam','I8O 4K4');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Regina J. Carey','(498) 747-3960','libero@odioAliquamvulputate.edu','Ap #675-1322 Ante Road','Nogales','L5Q 8X0','Wyoming','French Polynesia','Feb 3, 2014','T4A 1L7','Burton','(681) 780-1572','dictum@nasceturridiculusmus.com','Macon','51691');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Lisandra W. Flynn','(139) 501-1928','Nunc.lectus.pede@dapibusligulaAliquam.edu','9979 Faucibus. Rd.','Colorado Springs','N7T 6J7','YT','Grenada','Dec 24, 2013','O4K 6P3','Uta','(522) 552-7107','amet@pede.ca','Suffolk','S6J 7F3');
INSERT INTO employees (name,phone,email,addres,city,zip,state,country,date,custom,rname,ophone,altemail,altcity,altzip) VALUES ('Aretha W. Roach','(544) 839-0636','orci.Donec.nibh@mollislectuspede.ca','P.O. Box 165, 1056 Magna. St.','Valdosta','U5V 5S2','AK','Moldova','Oct 8, 2013','W3N 8Z8','Joan','(892) 772-8839','a.magna.Lorem@litoratorquentper.org','Diamond Bar','88498');

 CREATE TABLE organisations (
  company varchar(255) default NULL,
  location varchar(50) default NULL,
  date varchar(50) default NULL,
  description TEXT default NULL,
  longdesc TEXT default NULL
);

INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Pearl','Swaziland','Thu, 8th, 2013','pede et risus. Quisque libero lacus, varius et, euismod et,','placerat. Cras dictum ultricies ligula. Nullam enim. Sed');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Stacey','Aruba','Mon, 18th, 2013','quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus','auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Kessie','Bermuda','Wed, 6th, 2012','posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse','Vivamus sit');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Bianca','Uruguay','Thu, 17th, 2013','elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu','lobortis quam a');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Rhona','Slovenia','Sun, 23rd, 2013','at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas','tristique ac,');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Virginia','Aruba','Sat, 14th, 2012','erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat','felis orci, adipiscing non, luctus sit amet, faucibus ut,');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Mari','Morocco','Mon, 31st, 2012','nisl arcu iaculis enim, sit amet ornare lectus justo eu','Morbi sit amet massa. Quisque porttitor');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Selma','Heard Island and Mcdonald Islands','Fri, 14th, 2013','lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod','Donec sollicitudin adipiscing ligula. Aenean');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Megan','United Kingdom','Mon, 24th, 2012','in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum','fringilla. Donec feugiat metus sit amet');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Kimberly','Papua New Guinea','Thu, 10th, 2012','ut nisi a odio semper cursus. Integer mollis. Integer tincidunt','tortor at risus. Nunc');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Jaquelyn','Burundi','Thu, 24th, 2012','congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum','mauris. Morbi non sapien molestie orci');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Basia','Malaysia','Thu, 16th, 2013','dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu','Nam porttitor scelerisque neque. Nullam');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Rebecca','Belize','Sat, 12th, 2013','nec, leo. Morbi neque tellus, imperdiet non, vestibulum nec, euismod','lobortis');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Fallon','Trinidad and Tobago','Tue, 10th, 2013','Fusce feugiat. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.','Proin vel arcu eu odio tristique pharetra.');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Georgia','Ethiopia','Sat, 22nd, 2012','ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula.','nulla magna, malesuada vel, convallis in, cursus et,');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Indigo','Dominica','Thu, 13th, 2012','nec mauris blandit mattis. Cras eget nisi dictum augue malesuada','Nullam suscipit, est ac facilisis');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Kai','Trinidad and Tobago','Fri, 28th, 2012','scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia.','lectus rutrum');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Alfreda','Faroe Islands','Wed, 25th, 2013','Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla','Nullam vitae diam. Proin');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Ivory','Brunei Darussalam','Sat, 29th, 2012','Pellentesque habitant morbi tristique senectus et netus et malesuada fames','In mi pede, nonummy');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Joelle','Palestinian Territory, Occupied','Sun, 27th, 2013','mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed','mi enim, condimentum eget, volutpat');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Jena','Saint Lucia','Wed, 31st, 2013','ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci','lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Jolie','Bhutan','Thu, 6th, 2013','condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus','commodo');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Grace','Lebanon','Sat, 1st, 2014','sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum','ridiculus');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Xantha','Benin','Sat, 14th, 2013','arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut','sit amet, faucibus ut, nulla. Cras eu tellus eu augue');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Orli','Iceland','Fri, 10th, 2014','non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit','Integer eu lacus. Quisque imperdiet, erat');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Rhea','Antarctica','Fri, 22nd, 2013','lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque.','molestie tortor nibh sit amet orci. Ut sagittis lobortis');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Rina','Ghana','Mon, 18th, 2013','et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis','at, egestas a, scelerisque');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Octavia','Swaziland','Tue, 29th, 2013','cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum','egestas blandit. Nam nulla magna,');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Odessa','Samoa','Tue, 3rd, 2013','vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum','lorem eu');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Aline','Cambodia','Sat, 3rd, 2012','dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus','mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet,');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Ifeoma','Reunion','Mon, 3rd, 2012','dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero.','Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam.');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Hedda','Saint Helena','Fri, 15th, 2012','ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae,','Donec consectetuer mauris id sapien. Cras dolor dolor, tempus');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Sage','New Caledonia','Sat, 17th, 2012','pharetra ut, pharetra sed, hendrerit a, arcu. Sed et libero.','erat.');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Adena','Samoa','Mon, 21st, 2013','convallis in, cursus et, eros. Proin ultrices. Duis volutpat nunc','In mi');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Paloma','Taiwan, Province of China','Sun, 17th, 2013','pharetra sed, hendrerit a, arcu. Sed et libero. Proin mi.','orci');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Risa','Bhutan','Tue, 25th, 2013','amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis','est, mollis non, cursus non, egestas a, dui.');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Halla','Bermuda','Fri, 31st, 2014','porta elit, a feugiat tellus lorem eu metus. In lorem.','facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Camilla','Denmark','Fri, 8th, 2013','erat vitae risus. Duis a mi fringilla mi lacinia mattis.','ac turpis egestas. Fusce aliquet');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Jayme','France','Mon, 22nd, 2012','Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis,','lacus. Aliquam rutrum lorem');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Olivia','Iceland','Sun, 11th, 2012','eget odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam','Cras eget nisi dictum augue malesuada');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Ginger','Gambia','Sat, 15th, 2014','Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est.','turpis. Nulla aliquet.');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Justina','Belarus','Tue, 18th, 2012','purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula','nonummy ultricies ornare, elit elit fermentum risus,');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Maggy','Afghanistan','Sun, 8th, 2012','nisi sem semper erat, in consectetuer ipsum nunc id enim.','eget mollis lectus pede et');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Xantha','Moldova','Sat, 7th, 2013','Donec fringilla. Donec feugiat metus sit amet ante. Vivamus non','diam. Pellentesque habitant morbi tristique senectus et netus');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Christine','Colombia','Tue, 17th, 2012','felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem,','quis lectus. Nullam suscipit, est ac facilisis facilisis, magna');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Ocean','Namibia','Fri, 19th, 2013','tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu','lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Leila','Burkina Faso','Thu, 24th, 2012','dapibus id, blandit at, nisi. Cum sociis natoque penatibus et','Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Teagan','Kazakhstan','Mon, 30th, 2013','Donec nibh enim, gravida sit amet, dapibus id, blandit at,','eu eros. Nam consequat dolor');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Giselle','American Samoa','Fri, 1st, 2013','vitae dolor. Donec fringilla. Donec feugiat metus sit amet ante.','Sed auctor odio');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Adrienne','Cocos (Keeling) Islands','Fri, 22nd, 2012','metus eu erat semper rutrum. Fusce dolor quam, elementum at,','vel, mauris.');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Belle','Georgia','Mon, 16th, 2013','quis turpis vitae purus gravida sagittis. Duis gravida. Praesent eu','elit. Nulla facilisi. Sed neque.');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Quin','Cayman Islands','Fri, 29th, 2013','eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed','Aliquam auctor, velit eget laoreet posuere, enim nisl');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Alexa','Georgia','Sat, 21st, 2013','nibh. Donec est mauris, rhoncus id, mollis nec, cursus a,','porttitor eros nec tellus. Nunc lectus');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Leslie','Jordan','Sun, 4th, 2012','vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis.','neque');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Stacey','Hong Kong','Fri, 28th, 2012','volutpat nunc sit amet metus. Aliquam erat volutpat. Nulla facilisis.','dui augue eu tellus. Phasellus elit pede, malesuada vel, venenatis');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Gwendolyn','Albania','Wed, 9th, 2013','In at pede. Cras vulputate velit eu sem. Pellentesque ut','vitae nibh. Donec est');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Reagan','Kiribati','Wed, 4th, 2013','Duis elementum, dui quis accumsan convallis, ante lectus convallis est,','et nunc. Quisque ornare tortor at risus. Nunc ac sem');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Mona','Papua New Guinea','Thu, 19th, 2013','Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy','faucibus ut, nulla. Cras eu');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Autumn','Macao','Thu, 26th, 2013','metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec','mollis. Phasellus libero');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Athena','Serbia and Montenegro','Tue, 19th, 2013','rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed','nulla magna, malesuada vel, convallis in, cursus et, eros.');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Heidi','Pitcairn','Wed, 12th, 2012','sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos.','in aliquet lobortis,');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Sydney','Mauritania','Sun, 26th, 2012','nisi nibh lacinia orci, consectetuer euismod est arcu ac orci.','ut dolor dapibus gravida. Aliquam tincidunt, nunc ac');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Shana','Latvia','Thu, 14th, 2013','ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque','vehicula aliquet libero. Integer');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Gail','Virgin Islands, U.S.','Wed, 23rd, 2013','erat. Sed nunc est, mollis non, cursus non, egestas a,','nec tempus scelerisque, lorem');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Lavinia','Kuwait','Sat, 4th, 2013','vestibulum nec, euismod in, dolor. Fusce feugiat. Lorem ipsum dolor','massa lobortis ultrices. Vivamus');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Alyssa','Hungary','Sat, 26th, 2012','Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas','et ultrices posuere cubilia Curae; Phasellus');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Hayley','Tokelau','Wed, 5th, 2012','velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor','consequat dolor vitae dolor. Donec fringilla. Donec');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Maxine','Libyan Arab Jamahiriya','Wed, 9th, 2013','vel lectus. Cum sociis natoque penatibus et magnis dis parturient','nonummy ut, molestie in,');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Madonna','China','Wed, 25th, 2013','magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla','molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis.');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Blossom','Faroe Islands','Sun, 23rd, 2012','elementum, dui quis accumsan convallis, ante lectus convallis est, vitae','natoque penatibus et');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Veronica','Saint Vincent and The Grenadines','Mon, 11th, 2012','leo elementum sem, vitae aliquam eros turpis non enim. Mauris','odio. Nam interdum enim non nisi. Aenean eget metus. In');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Shannon','Uzbekistan','Tue, 1st, 2013','lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque.','ac mattis semper, dui');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Octavia','Palau','Sat, 15th, 2014','ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam','sapien molestie orci tincidunt adipiscing. Mauris molestie');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Kelsie','Falkland Islands (Malvinas)','Wed, 30th, 2013','eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer','eu tellus.');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Zena','Senegal','Sun, 20th, 2013','Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit','Sed nec metus facilisis lorem tristique aliquet.');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Flavia','Senegal','Thu, 20th, 2013','sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque','Fusce feugiat. Lorem ipsum dolor sit amet, consectetuer');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Pascale','Panama','Mon, 9th, 2013','egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla','tellus faucibus leo, in lobortis tellus justo sit amet');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('September','Reunion','Tue, 27th, 2012','malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna.','accumsan sed, facilisis vitae,');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Angela','Antarctica','Sun, 24th, 2012','Vestibulum ante ipsum primis in faucibus orci luctus et ultrices','sociis natoque penatibus et magnis');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Aileen','United Kingdom','Sun, 8th, 2013','ac, fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra','Nam consequat dolor vitae dolor. Donec fringilla. Donec');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Lydia','Serbia and Montenegro','Fri, 20th, 2012','accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus vulputate,','accumsan convallis, ante lectus');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Mollie','Panama','Tue, 27th, 2013','nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras','orci, in consequat enim diam vel arcu. Curabitur');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Deanna','Kiribati','Sat, 8th, 2013','vitae dolor. Donec fringilla. Donec feugiat metus sit amet ante.','dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Orla','Solomon Islands','Sun, 30th, 2012','neque. Nullam ut nisi a odio semper cursus. Integer mollis.','odio sagittis semper.');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Brynn','Greece','Tue, 8th, 2012','sagittis. Duis gravida. Praesent eu nulla at sem molestie sodales.','luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Shaeleigh','Tajikistan','Wed, 6th, 2013','quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam','Donec tempus, lorem fringilla ornare placerat, orci lacus');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Serena','Heard Island and Mcdonald Islands','Sat, 7th, 2012','amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor','Donec luctus aliquet odio. Etiam ligula tortor, dictum');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Teagan','Iceland','Thu, 27th, 2014','odio a purus. Duis elementum, dui quis accumsan convallis, ante','diam dictum');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Tamara','Heard Island and Mcdonald Islands','Wed, 13th, 2013','eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis','auctor');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Violet','Saint Helena','Wed, 15th, 2013','ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec,','Ut');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Genevieve','Bulgaria','Thu, 6th, 2012','erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus','eget laoreet posuere, enim nisl');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Carissa','French Polynesia','Thu, 30th, 2013','blandit. Nam nulla magna, malesuada vel, convallis in, cursus et,','est, mollis non, cursus non, egestas a, dui. Cras');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Kylie','Peru','Sat, 16th, 2013','In ornare sagittis felis. Donec tempor, est ac mattis semper,','risus varius orci, in consequat enim diam vel arcu. Curabitur');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Emerald','Tokelau','Tue, 11th, 2012','aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque','et pede. Nunc sed orci lobortis augue scelerisque');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Yetta','Netherlands','Fri, 16th, 2013','vestibulum, neque sed dictum eleifend, nunc risus varius orci, in','sapien. Cras dolor dolor, tempus non,');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Rina','Lithuania','Mon, 11th, 2013','Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam','id, blandit at, nisi. Cum sociis natoque penatibus et magnis');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Isabelle','Faroe Islands','Wed, 2nd, 2013','Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum','auctor, nunc nulla vulputate dui, nec tempus mauris');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Melinda','Ukraine','Fri, 3rd, 2014','orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique','mollis dui, in sodales elit erat');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Cathleen','Armenia','Fri, 27th, 2012','tempor, est ac mattis semper, dui lectus rutrum urna, nec','magna. Cras convallis convallis dolor. Quisque tincidunt');
INSERT INTO organisations (company,location,date,description,longdesc) VALUES ('Velma','Turks and Caicos Islands','Mon, 11th, 2013','accumsan neque et nunc. Quisque ornare tortor at risus. Nunc','pede. Praesent eu dui. Cum sociis natoque penatibus');

CREATE TABLE settings (
   tab   varchar(32) unique not null,
   value text default null
);

INSERT INTO settings (tab, value) VALUES ('organisations', 'company,location,date');
INSERT INTO settings (tab, value) VALUES ('employees', 'name,date,phone,rname');

